// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeXeGqWrewo1LJAlMZj0TRsqE0jJrhzMg',
    appId: '1:537717680583:web:6f6d4df6acf7e4e8a211e2',
    messagingSenderId: '537717680583',
    projectId: 'fir-1-bb804',
    authDomain: 'fir-1-bb804.firebaseapp.com',
    storageBucket: 'fir-1-bb804.appspot.com',
    measurementId: 'G-WFPWZ56NKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCARYaQUCGu1ZwwxYAAez407z62WJMmYHs',
    appId: '1:537717680583:android:80d29f130bd4ba40a211e2',
    messagingSenderId: '537717680583',
    projectId: 'fir-1-bb804',
    storageBucket: 'fir-1-bb804.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-N2Wk_6yVAf2UoQSeB__vv7arGuomfQk',
    appId: '1:537717680583:ios:c7ad49d59443e15da211e2',
    messagingSenderId: '537717680583',
    projectId: 'fir-1-bb804',
    storageBucket: 'fir-1-bb804.appspot.com',
    androidClientId: '537717680583-9m3u4ghe20i94066d3pu5nucvv83p0av.apps.googleusercontent.com',
    iosClientId: '537717680583-iuvi2ul6grilf52rfha90o5fp1abe5vk.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseWhy1',
  );
}
